{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0716a296",
   "metadata": {},
   "outputs": [],
   "source": [
    "# timeout으로 마지막 코드가 안 돌아감 & 파일 생성 코드가 없는데 미리 파일을 생성해둬야하나?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "ef810086",
   "metadata": {},
   "outputs": [],
   "source": [
    "# from selenium import webdriver\n",
    "# driver = webdriver.Chrome('C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\selenium\\webdriver\\chrome\\chromedriver.exe')\n",
    "# driver.get(\"https://www.naver.com\")\n",
    "# Ghibli profile picture"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "b2849062",
   "metadata": {},
   "outputs": [],
   "source": [
    "import threading\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "import time\n",
    "import urllib.request"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "f10e2633",
   "metadata": {},
   "outputs": [],
   "source": [
    "search = \"Ghibli profile picture\"\n",
    "driver = webdriver.Chrome('C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\selenium\\webdriver\\chrome\\chromedriver.exe')\n",
    "driver.get(\"https://www.google.co.kr/imghp?hl=ko&tab=wi&authuser=0&ogbl\")\n",
    "elem = driver.find_element_by_name(\"q\")\n",
    "elem.send_keys(search)\n",
    "elem.send_keys(Keys.RETURN)\n",
    "\n",
    "SCROLL_PAUSE_TIME = 3\n",
    "# Get scroll height\n",
    "last_height = driver.execute_script(\"return document.body.scrollHeight\")\n",
    "SAVE_FLAG = False\n",
    "def timeout(limit_time): #timeout\n",
    "    start = time.time()\n",
    "    while True:\n",
    "        if time.time() - start > limit_time or SAVE_FLAG:\n",
    "            raise Exception('timeout. or image saved.')\n",
    "\n",
    "while True: #검색 결과들을 스크롤해서 미리 로딩해둠.\n",
    "    # Scroll down to bottom\n",
    "    driver.execute_script(\"window.scrollTo(0, document.body.scrollHeight);\")\n",
    "    # Wait to load page\n",
    "    time.sleep(SCROLL_PAUSE_TIME)\n",
    "    # Calculate new scroll height and compare with last scroll height\n",
    "    new_height = driver.execute_script(\"return document.body.scrollHeight\")\n",
    "    if new_height == last_height:\n",
    "        try:\n",
    "            driver.find_element_by_css_selector(\".mye4qd\").click()\n",
    "        except:\n",
    "            break\n",
    "    last_height = new_height\n",
    "\n",
    "images = driver.find_elements_by_css_selector(\".rg_i.Q4LuWd\")\n",
    "count = 0\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9cac73c4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-63:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-64:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-65:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-66:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-67:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-68:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-69:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-70:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-71:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-72:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-73:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-74:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-75:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-76:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-77:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-78:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-79:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-80:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-82:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-83:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-84:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-85:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-86:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-87:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-88:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-89:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-90:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-91:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n",
      "Exception in thread Thread-92:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kcc\\AppData\\Local\\Temp/ipykernel_21680/1491809002.py\", line 16, in timeout\n",
      "    raise Exception('timeout. or image saved.')\n",
      "Exception: timeout. or image saved.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "for image in images:\n",
    "    SAVE_FLAG = False\n",
    "    timer = threading.Thread(target=timeout, args=(30,))\n",
    "    try:\n",
    "        image.click()\n",
    "        time.sleep(3)\n",
    "        timer.start()\n",
    "        #이미지의 XPath 를 붙여넣기 해준다. >> F12 를 눌러서 페이지 소스의 Element에서 찾아보면됨.\n",
    "        imgUrl = driver.find_element_by_xpath('//*[@id=\"Sva75c\"]/div/div/div[3]/div[2]/c-wiz/div/div[1]/div[1]/div[2]/div/a/img').get_attribute(\"src\")\n",
    "        urllib.request.urlretrieve(imgUrl, \"GHIBLIimages/\"+ search + \"_{0:04}\".format(count) + \".jpg\") #저장할 이미지의 경로 지정\n",
    "        print('Save images : ', \"images/\"+ search + \"_{0:04}\".format(count) + \".jpg\")\n",
    "        SAVE_FLAG = True\n",
    "        count += 1\n",
    "        if timer.is_alive():\n",
    "            timer.join()\n",
    "    except Exception as e:\n",
    "        if timer.is_alive():\n",
    "            timer.join()\n",
    "        pass\n",
    "print('driver end. Total images : ', count)\n",
    "driver.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "408d97f6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
